convert the strings
Collivery/Collivery-WooCommerce pull request #117
Opened 2023-07-13 10:56 UTC by Magnificent-Big-J

- PHP 8 doesn’t allow string variables to calculate integer variables, so the website crashes with a 500 Server Error when your plugin does shipping calculations for these quote only/non-shipping products.

2023-07-13 11:40 UTC, drallan approved these changes

2023-07-14 05:17 UTC, WilRyan approved these changes

2023-07-14 05:17 UTC, WilRyan requested changes
Update plugin version

2023-07-14 05:23 UTC, Magnificent-Big-J commented
Ready to be merged

2023-07-14 05:23 UTC, merged