disable accept button when running a request
Collivery/Collivery-WooCommerce pull request #93
Opened 2021-08-05 10:12 UTC by axolile

2021-08-05 10:38 UTC, WilRyan submitted a review, later dismissed

2021-08-05 10:40 UTC, WilRyan commented
Please bump the version number

2021-08-05 10:40 UTC, MarnuLombard requested changes

2021-08-05 10:40 UTC, MarnuLombard commented on MdsSupportingClasses/Collivery.php
> +        curl_setopt($client, CURLOPT_SSL_VERIFYPEER, false);
Stop disabling this!
There's no reason to disable it even in your local environment

2021-08-05 11:11 UTC, MarnuLombard approved these changes

2021-08-06 12:36 UTC, WilRyan approved these changes

2021-08-06 14:26 UTC, merged